docs(nef): Add experimental-features to command
Michael noted after demos that this doesn't work with the default Nix
config that is installed with Flox.

The original suggestion was to not use flakes, which I adapted because
it was kinder on the eyes for people that have used flakes, but that
also fails without `nix-command`:

    % NIX_CONFIG="experimental-features = " EDITOR=cat nix edit -f '<nixpkgs>' hello
    error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it